### ISSUE TITLE
news and changes

### ISSUE THREAD

**Issue by dalmore72** [Jasmeet181/mediaportal-cz-logos#5]
Slusnej Kanal TV renamed Rebel2 Slusnej Kanal

Slager TV new logo

Markiza +1 HD new channel

Nova+1 HD new channel
[New.zip](https://github.com/Jasmeet181/mediaportal-cz-logos/files/1333002/New.zip)

**Comment by Jasmeet181** [comment]
Thanks, I'd been waiting to see if someone from the MP community would report these so that I'd know that this package is being used. I don't believe that there are any users.
