### ISSUE TITLE
New logos

### ISSUE THREAD

**Issue by dalmore72** [Jasmeet181/mediaportal-cz-logos#7]
New logo Rebel2
Changes to Story4 and 5
[cz-logos.zip](https://github.com/Jasmeet181/mediaportal-cz-logos/files/1973871/cz-logos.zip)

**Comment by Jasmeet181** [comment]
Thanks Dalmore. Here are slightly bigger logos for [Film4](https://dtvnews.hu/sites/default/files/wide_images/film4_wide.png) and [Galaxy4](https://dtvnews.hu/sites/default/files/wide_images/galaxy4_wide.png) from [DTV News](https://dtvnews.hu/hirek/megujul-es-kibovul-a-dmc-televizios-portfolioja) if you need them.

**Comment by dalmore72** [comment]
Thanks
