### ISSUE TITLE
new vector logos (cs collectoin)

### ISSUE THREAD

**Issue by chocholousek** [Jasmeet181/mediaportal-cz-logos#8]
new cs collection logos as vector, please ad to git.
[cscollection.zip](https://github.com/Jasmeet181/mediaportal-cz-logos/files/3957035/cscollection.zip)

**Comment by chocholousek** [comment]
new vector logo RTVS Trojka, start 22.12.2019 Astra 23E and 0.8W.
[Trojka.zip](https://github.com/Jasmeet181/mediaportal-cz-logos/files/3969031/Trojka.zip)

**Comment by Jasmeet181** [comment]
Thanks, I've tried a different layout for CS Film/Horror since MP1 uses square logos and also added some logos from your recent AB-Forum posts.
