### ISSUE TITLE
rebrand Rik TV - JOJ Group SK

### ISSUE THREAD

**Issue by chocholousek** [Jasmeet181/mediaportal-cz-logos#9]
Rebrand Rik tv (only broadcast by joj group slovakia) on JOJKO as of 1.1.2020.
[Jojko.zip](https://github.com/Jasmeet181/mediaportal-cz-logos/files/3991352/Jojko.zip)

https://www.youtube.com/watch?v=OXMxI_mC8pA

**Comment by Jasmeet181** [comment]
Thanks chocholousek.
